[GOVCMSD8-257] [8.x-1.x] Update drupal/adminimal_admin_toolbar to 1.9.0 (from 8.x-1.8.0)
govCMS/govcms8-installer pull request #226
Opened 2019-02-26 05:22 UTC by suhyeonh1

### https://www.drupal.org/project/adminimal_admin_toolbar/releases/8.x-1.9
Release notes
Issue #3027760 by i-trokhanenko: Use $this->t() instead of t() in form
Issue #3023185 Fixed issue with patch not being applied properly
Fixed issue with active state color

2019-02-26 05:41 UTC, ruwanl approved these changes

2019-04-10 01:57 UTC, pandaskii requested changes
Please resolve the conflict in composer.json

2019-04-10 02:14 UTC, tobybellwood commented
composer.json conflict resolved

2019-04-10 02:17 UTC, pandaskii approved these changes

2019-04-10 02:18 UTC, merged