Support for inline media links via Linkit.
govCMS/govcms8-installer pull request #327
Opened 2019-09-19 20:15 UTC by srowlands

## Issue/motivation
Currently there is no way to link to media documents via the WYSIWYG editor without manually copying/pasting direct references to files from the media library.

This is not ideal for two reasons:
- Poor editor experience
- If you change a media entity file then links will break

You can embed media entities directly (e.g via media embed), but they do not render inline (e.g `Text with a <a href="/path/to/file.pdf">linked file</a>`) and are difficult/impossible to coerce into doing so without resorting to theme hackery.

## Resolution
This PR upgrades Linkit to beta9, which has support for core media entities. The bundled config will allow the core linking functionality via WYSIWYG to include media items.

<img width="564" alt="Screen Shot 2019-09-19 at 11 15 07 am" src="https://user-images.githubusercontent.com/1256274/65277657-3ac40d80-dadf-11e9-9cfc-75e4a35de307.png">

Links will update accordingly if the media entity has it's file replaced/renamed.

I'll submit a follow-up PR with improvements to default document embeds shortly.

2019-09-19 20:42 UTC, steveworley submitted a review, later dismissed

2019-10-15 05:21 UTC, govindmaloo commented
@steveworley : Please resolve conflict so this can be merged.

2019-10-15 22:29 UTC, pandaskii requested changes
Looks good, happy to merge it to distribution after the merge conflicts fixed and test passed.

2019-10-31 22:25 UTC, pandaskii approved these changes

2019-10-31 22:28 UTC, pandaskii commented
Looks good, this PR is ready to be merged after testing and approval

thanks

2019-11-13 23:36 UTC, merged