Add minisite 8.x-1.0
govCMS/govcms8-installer pull request #435
Opened 2020-03-24 04:11 UTC by pandaskii

This module provides the ability to upload static 'minisites' to a Drupal website and maintain the minisite's look and feel.

Please note this module does not actually import the minisite pages as Drupal nodes.

The minisite module provides an additional custom field which follows a user story that "Site editor can upload a zipped archive attached to a node, and automatically extract this into the files directory. When the node is deleted, it should clean up all files uploaded. If a zip file contains any not-allowed extensions, the entire upload must be aborted, and no files saved to the file system."

upload and extract minisite archives
file blacklisting
file whitelisting
permission control
Suggested approach was to upload a zipped archive attached to a node, and automatically extract this into the files directory. When the node is deleted, it should clean up all files uploaded. If a zip file contains any not-allowed extensions, the entire upload must be aborted, and no files saved to the file system.

https://www.drupal.org/project/minisite/releases/8.x-1.0

2020-03-24 04:19 UTC, fubarhouse submitted a review, later dismissed

2020-03-25 00:00 UTC, simesy submitted a review, later dismissed

2020-04-08 06:39 UTC, AlexSkrypnyk requested changes
Please use the newest version `1.1`

2020-04-14 07:30 UTC, AlexSkrypnyk submitted a review, later dismissed

2020-05-21 07:01 UTC, AMDS commented
The 8.x-1.2 version is released.

2020-05-21 07:14 UTC, AMDS commented
Patch to fix the D9 deprecated code issue for function file_uri_target()

2020-05-22 00:09 UTC, AlexSkrypnyk commented
@AMDS 
Thanks for providing the patch, but it should have been provided as a PR on GitHub version of the project (https://github.com/salsadigitalauorg/minisite) to make sure that it does not brake the functionality of the module.

I suggest to delay merging of this PR until the patch can be applied to Minisite in GitHub and a new version is released.

I'm keen to release `1.3` with this patch if someone can please open a PR in https://github.com/salsadigitalauorg/minisite.

2020-05-22 08:58 UTC, AlexSkrypnyk commented
Blocked this until `1.3` is released with D9 patch applied.
Can be tracked here https://github.com/salsadigitalauorg/minisite/pull/25

2020-05-22 10:29 UTC, AlexSkrypnyk commented
Version 1.3 released with applied patch. 
https://www.drupal.org/project/minisite/releases/8.x-1.3
@AMDS could you please update this PR to include `1.3`.

2020-05-22 10:29 UTC, AlexSkrypnyk commented on composer.json
> +        "drupal/minisite": "1.2",
please change to 1.3

2020-05-22 10:30 UTC, AlexSkrypnyk requested changes

2020-05-22 10:30 UTC, AlexSkrypnyk commented on composer.json
> +        "drupal/minisite": "1.2",
please update to 1.3

2020-05-22 10:30 UTC, AlexSkrypnyk commented on composer.json
> +            "drupal/minisite": {
please remove this as this patch is already applied to `1.3`

2020-05-27 23:25 UTC, AlexSkrypnyk approved these changes

2020-05-27 23:26 UTC, AlexSkrypnyk commented
Approved

2020-06-05 00:49 UTC, merged